import { ServiceItem } from '../types';

export interface KyivOfficialTariffInfo {
  category: string;
  name: string;
  provider: string;
  rate: number;
  unit: string;
  details: string;
  legalBase: string;
}

export const KYIV_OFFICIAL_TARIFFS: KyivOfficialTariffInfo[] = [
  {
    category: 'Електроенергія',
    name: 'Єдиний тариф для населення',
    provider: 'YASNO (ТОВ «Київські енергетичні послуги») / ДТЕК',
    rate: 4.32,
    unit: 'грн / кВт⋅год',
    details: 'Діє єдиний тариф 4,32 грн/кВт⋅год (продовжено урядом до 31 жовтня 2026 року). Для двозонних лічильників у нічний час (23:00-07:00) діє знижка 50% — 2,16 грн/кВт⋅год. З 1 жовтня на період опалювального сезону діятиме 2,64 грн для електроопалення.',
    legalBase: 'Постанова КМУ №632 (продовжено до 31.10.2026)',
  },
  {
    category: 'Холодна вода та стоки',
    name: 'Централізоване водопостачання та водовідведення',
    provider: 'ПрАТ «АК «Київводоканал»',
    rate: 63.79,
    unit: 'грн / м³',
    details: 'Рішення Київради від вересня 2026 р.: водопостачання 35,88 грн/м³ + водовідведення 27,91 грн/м³ = 63,79 грн/м³ (раніше 30,384 грн/м³). Абонплата у 2026 р. становить до 47,19 грн окремо за воду та стоки.',
    legalBase: 'Рішення Київради від вересня 2026 р. / Тариф НКРЕКП',
  },
  {
    category: 'Гаряча вода',
    name: 'Централізоване гаряче водопостачання',
    provider: 'КП «Київтеплоенерго»',
    rate: 97.89,
    unit: 'грн / м³',
    details: 'Мораторій на період воєнного стану та 6 місяців після нього фіксує пільговий тариф 97,89 грн/м³.',
    legalBase: 'Закон України про мораторій на підвищення тарифів',
  },
  {
    category: 'Опалення',
    name: 'Централізоване опалення (за лічильником / за площею)',
    provider: 'КП «Київтеплоенерго»',
    rate: 1654.41,
    unit: 'грн / Гкал (або ~38.50 грн/м²)',
    details: 'Зафіксовано мораторієм: 1654,41 грн/Гкал або ~38,50 грн за 1 м² опалювальної площі. На 1 вересня опалення вимкнено (сезон розпочинається в середині жовтня).',
    legalBase: 'Фіксований тариф КП Київтеплоенерго (мораторій)',
  },
  {
    category: 'Газ',
    name: 'Постачання природного газу',
    provider: 'ТОВ «ГК «Нафтогаз України»',
    rate: 7.96,
    unit: 'грн / м³',
    details: 'Фіксований тариф 7,96 грн/м³ гарантовано в межах річного тарифного плану «Фіксований» щонайменше до 30 квітня 2027 року.',
    legalBase: 'Тариф ГК Нафтогаз України (до 30.04.2027)',
  },
  {
    category: 'Доставка газу',
    name: 'Розподіл природного газу',
    provider: 'АТ «Київгаз»',
    rate: 0.384,
    unit: 'грн / м³ (або фікс. абонплата)',
    details: 'Оплата за розподіл газу зафіксована на період воєнного стану (зазвичай 18–35 грн/міс. залежно від споживання за попередній газовий рік).',
    legalBase: 'Тариф АТ Київгаз (мораторій НКРЕКП)',
  },
  {
    category: 'Квартплата',
    name: 'Утримання будинку та прибудинкової території',
    provider: 'Керуюча компанія району Києва / ОСББ / ЖБК',
    rate: 9.50,
    unit: 'грн / м²',
    details: 'Індивідуально для кожного будинку (середній міський рівень у 2026 році: 8.50 – 12.00 грн за 1 м² площі).',
    legalBase: 'Договір з керуючою компанією / рішення ОСББ',
  },
  {
    category: 'Вивіз сміття',
    name: 'Поводження з побутовими відходами',
    provider: 'КП «Київкомунсервіс»',
    rate: 46.37,
    unit: 'грн / ос. на місяць',
    details: 'Нараховується на кожну зареєстровану (прописану) особу в квартирі (46,37 грн/люд.).',
    legalBase: 'Розпорядження КМДА / КП Київкомунсервіс',
  },
];

export const MONTH_NAMES_UA = [
  'Січень', 'Лютий', 'Березень', 'Квітень', 'Травень', 'Червень',
  'Липень', 'Серпень', 'Вересень', 'Жовтень', 'Листопад', 'Грудень'
];

export const MONTH_NAMES_RU = MONTH_NAMES_UA;

export function getDefaultServices(): ServiceItem[] {
  return [
    {
      id: 'electricity',
      category: 'electricity',
      name: 'Електроенергія',
      provider: 'YASNO / ДТЕК Київські електромережі',
      isEnabled: true,
      calcMode: 'meters',
      prevReading: 1240,
      currReading: 1385,
      consumption: 145,
      hasTwoZones: false,
      prevReadingNight: 410,
      currReadingNight: 460,
      consumptionNight: 50,
      tariff: 4.32,
      tariffNight: 2.16,
      abonplata: 0,
      unit: 'кВт⋅год',
      totalCost: 626.40,
    },
    {
      id: 'cold_water',
      category: 'cold_water',
      name: 'Холодна вода та водовідведення',
      provider: 'Київводоканал',
      isEnabled: true,
      calcMode: 'meters',
      prevReading: 182,
      currReading: 188,
      consumption: 6,
      tariff: 63.79,
      abonplata: 40.00,
      unit: 'м³',
      totalCost: 422.74,
    },
    {
      id: 'hot_water',
      category: 'hot_water',
      name: 'Гаряча вода',
      provider: 'Київтеплоенерго',
      isEnabled: true,
      calcMode: 'meters',
      prevReading: 95,
      currReading: 98,
      consumption: 3,
      tariff: 97.89,
      abonplata: 25.00,
      unit: 'м³',
      totalCost: 318.67,
    },
    {
      id: 'heating',
      category: 'heating',
      name: 'Опалення (в сезон)',
      provider: 'Київтеплоенерго',
      isEnabled: true,
      calcMode: 'norm_sqm',
      prevReading: '',
      currReading: '',
      consumption: 52,
      tariff: 38.50,
      abonplata: 20.00,
      unit: 'м²',
      totalCost: 2022.00,
    },
    {
      id: 'gas',
      category: 'gas',
      name: 'Газ (споживання)',
      provider: 'Нафтогаз України',
      isEnabled: true,
      calcMode: 'meters',
      prevReading: 312,
      currReading: 320,
      consumption: 8,
      tariff: 7.96,
      abonplata: 0,
      unit: 'м³',
      totalCost: 63.68,
    },
    {
      id: 'gas_delivery',
      category: 'gas',
      name: 'Доставка / розподіл газу',
      provider: 'Київгаз',
      isEnabled: true,
      calcMode: 'fixed',
      prevReading: '',
      currReading: '',
      consumption: 1,
      tariff: 24.50,
      abonplata: 0,
      unit: 'міс.',
      totalCost: 24.50,
    },
    {
      id: 'maintenance',
      category: 'maintenance',
      name: 'Квартплата (утримання будинку та двору)',
      provider: 'Керуюча компанія / ОСББ',
      isEnabled: true,
      calcMode: 'norm_sqm',
      prevReading: '',
      currReading: '',
      consumption: 52,
      tariff: 9.50,
      abonplata: 0,
      unit: 'м²',
      totalCost: 494.00,
    },
    {
      id: 'garbage',
      category: 'garbage',
      name: 'Вивіз сміття (ТПВ)',
      provider: 'Київкомунсервіс',
      isEnabled: true,
      calcMode: 'norm_person',
      prevReading: '',
      currReading: '',
      consumption: 2,
      tariff: 46.37,
      abonplata: 0,
      unit: 'ос.',
      totalCost: 92.74,
    },
    {
      id: 'intercom',
      category: 'other',
      name: 'Домофон',
      provider: 'Домофонсервіс',
      isEnabled: true,
      calcMode: 'fixed',
      prevReading: '',
      currReading: '',
      consumption: 1,
      tariff: 45.00,
      abonplata: 0,
      unit: 'міс.',
      totalCost: 45.00,
    },
    {
      id: 'internet',
      category: 'other',
      name: 'Інтернет та ТБ',
      provider: 'Провайдер (Lanet / Воля / Київстар)',
      isEnabled: false,
      calcMode: 'fixed',
      prevReading: '',
      currReading: '',
      consumption: 1,
      tariff: 250.00,
      abonplata: 0,
      unit: 'міс.',
      totalCost: 250.00,
    },
  ];
}
