import { ServiceItem } from '../types';

export interface KyivOfficialTariffInfo {
  category: string;
  name: string;
  provider: string;
  rate: number;
  unit: string;
  details: string;
  legalBase: string;
}

export const KYIV_OFFICIAL_TARIFFS: KyivOfficialTariffInfo[] = [
  {
    category: 'Електроенергія',
    name: 'Єдиний тариф для населення',
    provider: 'YASNO (ТОВ «Київські енергетичні послуги») / ДТЕК',
    rate: 4.32,
    unit: 'грн / кВт⋅год',
    details: 'Діє єдиний тариф 4,32 грн/кВт⋅год (продовжено урядом до 31 жовтня 2026 року). Для двозонних лічильників у нічний час (23:00-07:00) діє знижка 50% — 2,16 грн/кВт⋅год. З 1 жовтня на період опалювального сезону діятиме 2,64 грн для електроопалення.',
    legalBase: 'Постанова КМУ №632 (продовжено до 31.10.2026)',
  },
  {
    category: 'Холодна вода та стоки',
    name: 'Централізоване водопостачання та водовідведення',
    provider: 'ПрАТ «АК «Київводоканал»',
    rate: 63.79,
    unit: 'грн / м³',
    details: 'Рішення Київради від вересня 2026 р.: водопостачання 35,88 грн/м³ + водовідведення 27,91 грн/м³ = 63,79 грн/м³ (раніше 30,384 грн/м³). Абонплата у 2026 р. становить до 47,19 грн окремо за воду та стоки.',
    legalBase: 'Рішення Київради від вересня 2026 р. / Тариф НКРЕКП',
  },
  {
    category: 'Гаряча вода',
    name: 'Централізоване гаряче водопостачання',
    provider: 'КП «Київтеплоенерго»',
    rate: 97.89,
    unit: 'грн / м³',
    details: 'Мораторій на період воєнного стану та 6 місяців після нього фіксує пільговий тариф 97,89 грн/м³.',
    legalBase: 'Закон України про мораторій на підвищення тарифів',
  },
  {
    category: 'Опалення',
    name: 'Централізоване опалення (за лічильником / за площею)',
    provider: 'КП «Київтеплоенерго»',
    rate: 1654.41,
    unit: 'грн / Гкал (або ~38.50 грн/м²)',
    details: 'Зафіксовано мораторієм: 1654,41 грн/Гкал або ~38,50 грн за 1 м² опалювальної площі. На 1 вересня опалення вимкнено (сезон розпочинається в середині жовтня).',
    legalBase: 'Фіксований тариф КП Київтеплоенерго (мораторій)',
  },
  {
    category: 'Газ',
    name: 'Постачання природного газу',
    provider: 'ТОВ «ГК «Нафтогаз України»',
    rate: 7.96,
    unit: 'грн / м³',
    details: 'Фіксований тариф 7,96 грн/м³ гарантовано в межах річного тарифного плану «Фіксований» щонайменше до 30 квітня 2027 року.',
    legalBase: 'Тариф ГК Нафтогаз України (до 30.04.2027)',
  },
  {
    category: 'Доставка газу',
    name: 'Розподіл природного газу',
    provider: 'АТ «Київгаз»',
    rate: 0.384,
    unit: 'грн / м³ (або фікс. абонплата)',
    details: 'Оплата за розподіл газу зафіксована на період воєнного стану (зазвичай 18–35 грн/міс. залежно від споживання за попередній газовий рік).',
    legalBase: 'Тариф АТ Київгаз (мораторій НКРЕКП)',
  },
  {
    category: 'Квартплата',
    name: 'Утримання будинку та прибудинкової території',
    provider: 'Керуюча компанія району Києва (КП / ОСББ / приватна)',
    rate: 12.84,
    unit: 'грн / м²',
    details: 'З березня 2025 – 2026 рр. у Києві проведено конкурси управителів: середні тарифи комунальних керуючих компаній 10 районів становлять 12.20 – 13.80 грн/м² (раніше 7-8 грн). В ОСББ внески складають 15–22 грн/м², у новобудовах — 18–30 грн/м².',
    legalBase: 'Результати міського конкурсу управителів / Договір з КП району або ОСББ',
  },
  {
    category: 'Вивіз сміття',
    name: 'Поводження з побутовими відходами',
    provider: 'КП «Київкомунсервіс»',
    rate: 46.37,
    unit: 'грн / ос. на місяць',
    details: 'Нараховується на кожну зареєстровану (прописану) особу в квартирі (46,37 грн/люд.).',
    legalBase: 'Розпорядження КМДА / КП Київкомунсервіс',
  },
];

export const MONTH_NAMES_UA = [
  'Січень', 'Лютий', 'Березень', 'Квітень', 'Травень', 'Червень',
  'Липень', 'Серпень', 'Вересень', 'Жовтень', 'Листопад', 'Грудень'
];

export const MONTH_NAMES_RU = MONTH_NAMES_UA;

export interface KyivDistrictInfo {
  id: string;
  name: string;
  shortName: string;
  managingCompany: string;
  rate: number; // грн / м² (середній актуальний тариф 2025-2026)
  rateRange: string; // діапазон тарифів у районі
  notes: string;
}

export const KYIV_DISTRICTS: KyivDistrictInfo[] = [
  {
    id: 'obolonskyi',
    name: 'Оболонський район',
    shortName: 'Оболонь',
    managingCompany: 'КП «Керуюча компанія Оболонського району»',
    rate: 12.84,
    rateRange: '12.50 – 13.08 грн/м²',
    notes: 'Типові панельні та цегляні будинки Оболоні, Мінського масиву та Пріорки',
  },
  {
    id: 'pecherskyi',
    name: 'Печерський район',
    shortName: 'Печерськ',
    managingCompany: 'КП «Керуюча компанія Печерського району»',
    rate: 13.80,
    rateRange: '13.20 – 14.50 грн/м²',
    notes: 'Центр столиці, висока частка історичного житлофонду та вищі експлуатаційні витрати',
  },
  {
    id: 'shevchenkivskyi',
    name: 'Шевченківський район',
    shortName: 'Шевченківський',
    managingCompany: 'КП «Керуюча компанія Шевченківського району»',
    rate: 13.60,
    rateRange: '13.00 – 13.94 грн/м²',
    notes: 'Центр, Лук’янівка, Сирець, Нивки: дореволюційні та сталінські будинки',
  },
  {
    id: 'holosiivskyi',
    name: 'Голосіївський район',
    shortName: 'Голосієво',
    managingCompany: 'КП «Керуюча компанія Голосіївського району»',
    rate: 12.75,
    rateRange: '12.50 – 13.10 грн/м²',
    notes: 'Голосіїв, Деміївка, Теремки-1 та Теремки-2',
  },
  {
    id: 'darnytskyi',
    name: 'Дарницький район',
    shortName: 'Дарниця (Лівий берег)',
    managingCompany: 'КП «Керуюча компанія Дарницького району»',
    rate: 12.60,
    rateRange: '12.40 – 12.95 грн/м²',
    notes: 'Позняки, Осокорки, Харківський: великі багатоповерхові масиви',
  },
  {
    id: 'desnianskyi',
    name: 'Деснянський район',
    shortName: 'Деснянський (Троєщина)',
    managingCompany: 'КП «Керуюча компанія Деснянського району»',
    rate: 12.20,
    rateRange: '11.80 – 12.60 грн/м²',
    notes: 'Троєщина та Лісовий масив: типова багатоповерхова забудова з оптимізованими витратами',
  },
  {
    id: 'dniprovskyi',
    name: 'Дніпровський район',
    shortName: 'Дніпровський',
    managingCompany: 'КП «Керуюча компанія Дніпровського району»',
    rate: 12.50,
    rateRange: '12.20 – 12.80 грн/м²',
    notes: 'Русанівка, Березняки, Воскресенка, Дарниця, Райдужний',
  },
  {
    id: 'podilskyi',
    name: 'Подільський район',
    shortName: 'Поділ',
    managingCompany: 'КП «Керуюча компанія Подільського району»',
    rate: 13.10,
    rateRange: '12.80 – 13.50 грн/м²',
    notes: 'Історичний Поділ, Куренівка, Мостицький масив, Виноградар',
  },
  {
    id: 'sviatoshynskyi',
    name: 'Святошинський район',
    shortName: 'Святошин',
    managingCompany: 'КП «Керуюча компанія Святошинського району»',
    rate: 12.45,
    rateRange: '12.10 – 12.75 грн/м²',
    notes: 'Борщагівка, Святошин, Академмістечко, Біличі',
  },
  {
    id: 'solomianskyi',
    name: 'Солом\'янський район',
    shortName: 'Солом\'янка',
    managingCompany: 'КП «Керуюча компанія Солом\'янського району»',
    rate: 12.65,
    rateRange: '12.30 – 12.90 грн/м²',
    notes: 'Солом\'янка, Чоколівка, Відрадний, Караваєві Дачі',
  },
  {
    id: 'osbb',
    name: 'ОСББ / ЖБК (середній внесок)',
    shortName: 'ОСББ / ЖБК',
    managingCompany: 'Об’єднання співвласників багатоквартирного будинку',
    rate: 18.00,
    rateRange: '15.00 – 22.00 грн/м²',
    notes: 'Внесок на утримання будинку, консьєржа, відеоспостереження та ремонтний фонд ОСББ',
  },
  {
    id: 'private',
    name: 'Приватна КК / Новобудова',
    shortName: 'Приватна керуюча компанія',
    managingCompany: 'Приватна управляюча компанія',
    rate: 22.50,
    rateRange: '18.00 – 30.00 грн/м²',
    notes: 'ЖК комфорт-, бізнес- та преміум-класу (охорона, закрита територія, прибирання, консьєрж)',
  },
  {
    id: 'custom',
    name: 'Власний тариф з платіжки',
    shortName: 'Індивідуальний тариф',
    managingCompany: 'Управитель вашого будинку',
    rate: 12.50,
    rateRange: 'Встановлюється за договором',
    notes: 'Введіть точну ставку вашого будинку вручну',
  },
];

export function getKyivDistrict(districtId?: string): KyivDistrictInfo {
  if (!districtId) return KYIV_DISTRICTS[0];
  const found = KYIV_DISTRICTS.find((d) => d.id === districtId);
  return found || KYIV_DISTRICTS[0];
}

export function getDefaultServices(): ServiceItem[] {
  return [
    {
      id: 'electricity',
      category: 'electricity',
      name: 'Електроенергія',
      provider: 'YASNO / ДТЕК Київські електромережі',
      isEnabled: true,
      calcMode: 'meters',
      prevReading: 1240,
      currReading: 1385,
      consumption: 145,
      hasTwoZones: false,
      prevReadingNight: 410,
      currReadingNight: 460,
      consumptionNight: 50,
      tariff: 4.32,
      tariffNight: 2.16,
      abonplata: 0,
      unit: 'кВт⋅год',
      totalCost: 626.40,
    },
    {
      id: 'cold_water',
      category: 'cold_water',
      name: 'Холодна вода та водовідведення',
      provider: 'Київводоканал',
      isEnabled: true,
      calcMode: 'meters',
      prevReading: 182,
      currReading: 188,
      consumption: 6,
      tariff: 63.79,
      abonplata: 40.00,
      unit: 'м³',
      totalCost: 422.74,
    },
    {
      id: 'hot_water',
      category: 'hot_water',
      name: 'Гаряча вода',
      provider: 'Київтеплоенерго',
      isEnabled: true,
      calcMode: 'meters',
      prevReading: 95,
      currReading: 98,
      consumption: 3,
      tariff: 97.89,
      abonplata: 25.00,
      unit: 'м³',
      totalCost: 318.67,
    },
    {
      id: 'heating',
      category: 'heating',
      name: 'Опалення (в сезон)',
      provider: 'Київтеплоенерго',
      isEnabled: true,
      calcMode: 'norm_sqm',
      prevReading: '',
      currReading: '',
      consumption: 52,
      tariff: 38.50,
      abonplata: 20.00,
      unit: 'м²',
      totalCost: 2022.00,
    },
    {
      id: 'gas',
      category: 'gas',
      name: 'Газ (споживання)',
      provider: 'Нафтогаз України',
      isEnabled: true,
      calcMode: 'meters',
      prevReading: 312,
      currReading: 320,
      consumption: 8,
      tariff: 7.96,
      abonplata: 0,
      unit: 'м³',
      totalCost: 63.68,
    },
    {
      id: 'gas_delivery',
      category: 'gas',
      name: 'Доставка / розподіл газу',
      provider: 'Київгаз',
      isEnabled: true,
      calcMode: 'fixed',
      prevReading: '',
      currReading: '',
      consumption: 1,
      tariff: 24.50,
      abonplata: 0,
      unit: 'міс.',
      totalCost: 24.50,
    },
    {
      id: 'maintenance',
      category: 'maintenance',
      name: 'Квартплата (утримання будинку та двору)',
      provider: 'КП «Керуюча компанія Оболонського району»',
      isEnabled: true,
      calcMode: 'norm_sqm',
      prevReading: '',
      currReading: '',
      consumption: 52,
      tariff: 12.84,
      abonplata: 0,
      unit: 'м²',
      totalCost: 667.68,
    },
    {
      id: 'garbage',
      category: 'garbage',
      name: 'Вивіз сміття (ТПВ)',
      provider: 'Київкомунсервіс',
      isEnabled: true,
      calcMode: 'norm_person',
      prevReading: '',
      currReading: '',
      consumption: 2,
      tariff: 46.37,
      abonplata: 0,
      unit: 'ос.',
      totalCost: 92.74,
    },
    {
      id: 'intercom',
      category: 'other',
      name: 'Домофон',
      provider: 'Домофонсервіс',
      isEnabled: true,
      calcMode: 'fixed',
      prevReading: '',
      currReading: '',
      consumption: 1,
      tariff: 45.00,
      abonplata: 0,
      unit: 'міс.',
      totalCost: 45.00,
    },
    {
      id: 'internet',
      category: 'other',
      name: 'Інтернет та ТБ',
      provider: 'Провайдер (Lanet / Воля / Київстар)',
      isEnabled: false,
      calcMode: 'fixed',
      prevReading: '',
      currReading: '',
      consumption: 1,
      tariff: 250.00,
      abonplata: 0,
      unit: 'міс.',
      totalCost: 250.00,
    },
  ];
}
